// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tool.Calendar.Repository.MysqlEFCore;

namespace Tool.Calendar.Repository.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20190416035219_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Tool.Calendar.Models.Models.T_ConsumptionType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConsumptionTypeClass");

                    b.Property<DateTime>("ConsumptionTypeCreateDate");

                    b.Property<byte[]>("ConsumptionTypeGuid")
                        .IsRequired()
                        .HasConversion(new ValueConverter<byte[], byte[]>(v => default(byte[]), v => default(byte[]), new ConverterMappingHints(size: 16)));

                    b.Property<string>("ConsumptionTypeName");

                    b.HasKey("ID");

                    b.ToTable("t_ConsumptionTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
