// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tool.Calendar.DAL;

namespace Tool.Calendar.DAL.Migrations
{
    [DbContext(typeof(ConsumptionTypeContext))]
    partial class ConsumptionTypeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Tool.Calendar.Model.ConsumptionType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CTDescription")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("CTLabelClass")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("CTName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("CTSort");

                    b.Property<DateTime>("CreteTime");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
